[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfuzzy-toolbox"
dynamic = ["version"]
description = "A comprehensive Python library for fuzzy systems: inference (Mamdani, Sugeno), learning (ANFIS, Wang-Mendel), and dynamics (p-fuzzy, fuzzy ODEs)"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Moiseis Cecconello", email = "moiseis@gmail.com"}
]
maintainers = [
    {name = "Moiseis Cecconello", email = "moiseis@gmail.com"}
]
keywords = [
    "fuzzy logic",
    "p-fuzzy systems",
    "fuzzy inference",
    "mamdani",
    "sugeno",
    "anfis",
    "wang-mendel",
    "machine learning",
    "fuzzy ode",
    "p-fuzzy",
    "artificial intelligence",
    "control systems"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=1.20.0",
    "matplotlib>=3.3.0",
    "scipy>=1.6.0",
]

[project.optional-dependencies]
ml = [
    "scikit-learn>=0.24",
    "pandas>=1.2",
    "joblib>=1.0",
]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.12",
    "black>=21.0",
    "flake8>=3.9",
    "mypy>=0.910",
]
docs = [
    "sphinx>=4.0",
    "sphinx-rtd-theme>=0.5",
    "nbsphinx>=0.8",
]
all = [
    "scikit-learn>=0.24",
    "pandas>=1.2",
    "joblib>=1.0",
    "pytest>=6.0",
    "pytest-cov>=2.12",
    "black>=21.0",
    "flake8>=3.9",
    "mypy>=0.910",
]

[project.urls]
Homepage = "https://github.com/1moi6/pyfuzzy-toolbox"
Documentation = "https://github.com/1moi6/pyfuzzy-toolbox#readme"
Repository = "https://github.com/1moi6/pyfuzzy-toolbox"
"Bug Tracker" = "https://github.com/1moi6/pyfuzzy-toolbox/issues"
Changelog = "https://github.com/1moi6/pyfuzzy-toolbox/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["fuzzy_systems"]

[tool.setuptools.dynamic]
version = {attr = "fuzzy_systems.__version__"}

[tool.setuptools.package-data]
fuzzy_systems = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --strict-markers"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
