name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-with-pdf

      - name: Deploy to GitHub Pages (without PDF)
        run: mkdocs gh-deploy --force
        env:
          # Don't generate PDF in CI (requires weasyprint dependencies)
          ENABLE_PDF_EXPORT: "0"
